M48
; DRILL file {KiCad (6.0.9-0)} date Tuesday, March 14, 2023 at 05:35:53 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-14T17:35:53-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0228
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T2
X5.4216Y-4.4735
T3
X4.5Y-4.9
X5.0Y-4.9
X6.1Y-4.9
X6.15Y-3.0
X6.4Y-3.0
X6.6Y-4.9
T1
G00X5.7086Y-4.4735
M15
G01X5.7251Y-4.4735
M16
G05
T0
M30
